name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: dropdown
    id: game-version
    attributes:
      label: Game Version
      description: Which version of the game are you playing?
      options:
        - Global
        - China
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What were you trying to do and expected to happen?
      placeholder: Tell us what you hoped for.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What happened instead?
      placeholder: Tell us what went wrong.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction Steps
      description: How can this bug be reproduced?
      placeholder: Tell us how to break it.
  - type: textarea
    id: logs
    attributes:
      label: RebornBuddy Log
      description: Please attach the correct log file in `RebornBuddy/Logs/`. If unsure which file, sort by Last Modified and pick the most recent.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Other Information
      options:
        - label: This issue is a bug, not a feature request or question.
          required: true
        - label: RebornBuddy and all add-ons have been updated to latest.
          required: true
        - label: No identifying information (e.g., character name) is being submitted.
          required: true
